### PR TITLE
Send email to admin when CI build item queued 3 times. 

### PR DESCRIPTION
**Pull request by Moo64c**
#213

Depends on #210 - don't merge before it's merged.

### CODE REVIEW

**Comment by amitaibu** [comment]
screenshot of the message sent please (hard to read from the code)

**Comment by Moo64c** [comment]
selection_139

The title is the same as the first line.
selection_140

@amitaibu I'll update when I'll finish fixing the title.

**Comment by Moo64c** [comment]
@amitaibu New message look:
selection_141

**Comment by Moo64c** [comment]
@amitaibu Re-rolled this too.

**Comment by amitaibu** [comment]
Merged.

**Pull request closed without merging**
