### PR TITLE
Return file content

### PR DESCRIPTION
**Pull request by HelenaEksler**

### CODE REVIEW

**Comment by HelenaEksler** [comment]
After this change:
http://localhost/shoov/www/api/v1.0/ci-build-status/9 - returns image:
selection_049

Link can be used as `scr` for images:
selection_050

**Comment by HelenaEksler** [comment]
@amitaibu ^^

**Comment by amitaibu** [comment]
@HelenaEksler the screenshot should be from within a page in Github/ Gist.

**Comment by HelenaEksler** [comment]
I can't test it with localhost url... 
Even `image` 
is not displayed. Is there some other way?

**Comment by HelenaEksler** [comment]
@amitaibu It' working file with `file_get_contents()`. The only thing - we should pass `status_token` in the URL, because github when trying to get the image - it's like an anonymous user:
`status`
status-passing
status-unconfirmed
status-errored

**Comment by amitaibu** [comment]
@HelenaEksler I'm not seeing the images, can attach a screenshot of the comment

**Comment by amitaibu** [comment]
@HelenaEksler ready for review?

**Pull request merged**
