### PR TITLE
If user doesn't have any content yet show them intro box on the homepage

### PR DESCRIPTION
**Pull request by HelenaEksler**
#234

### CODE REVIEW

**Comment by HelenaEksler** [comment]
shoov-demo

**Comment by amitaibu** [comment]
Lets add also sending an email to admin, when demo URL is added

**Comment by HelenaEksler** [comment]
selection_130

**Comment by amitaibu** [comment]
:+1:

**Comment by niryariv** [comment]
remove "not sure what to do?"

**Comment by HelenaEksler** [comment]
selection_001

**Comment by HelenaEksler** [comment]
@amitaibu @niryariv Ready.

**Comment by HelenaEksler** [comment]
@amitaibu Is it still relevant? https://github.com/shoov/shoov/blob/master/client/app/views/dashboard/homepage.html#L40-L52

**Comment by amitaibu** [comment]
This was already merged

**Pull request closed without merging**
