### PR TITLE
Add view to show user's recent nodes in user's page

### PR DESCRIPTION
**Pull request by HelenaEksler**
#125
#151

### CODE REVIEW

**Comment by HelenaEksler** [comment]
selection_025

**Comment by amitaibu** [comment]
Make as table.

**Comment by HelenaEksler** [comment]
selection_027

**Comment by HelenaEksler** [comment]
I've limited to 25 recent nodes. Should I change the date format to short one ( d/m/Y H:i)?

**Comment by amitaibu** [comment]
Change title "My recent .." => "%arg1 recent .."

**Comment by amitaibu** [comment]
Also add text when no content created yet.

**Comment by amitaibu** [comment]
@HelenaEksler I've merged this, thanks. Please take care of the minor comments in a follow up.

**Pull request closed without merging**
