### PR TITLE
Travis check

### PR DESCRIPTION
**Pull request by HelenaEksler**

### CODE REVIEW

**Comment by HelenaEksler** [comment]
@amitaibu Travis is failing on `$DRUSH make --no-core --contrib-destination drupal-org.make` command

**Comment by HelenaEksler** [comment]
With seven drush works, but tests are failing. Will try different versions of 6

**Comment by HelenaEksler** [comment]
@amitaibu `drush rs` without mentioning port server should run on Port 8888 (like this it runs locally). Waiting Travis to get to the point.

**Comment by HelenaEksler** [comment]
selection_045
As I can see from log (I've used `--debug` option) - server is running. So probably something else causes the problem

**Comment by HelenaEksler** [comment]
@amitaibu Ready :) 
1. Changed drush version to 7
2. Run server not with drush, but with php.
3. Show server logs (I would suggest to leave showing logs for future)

**Comment by amitaibu** [comment]
@HelenaEksler (and @RoySegall) great work! 

@HelenaEksler can you please merge squash.

**Comment by amitaibu** [comment]
Merged, thanks.

**Pull request closed without merging**
