### PR TITLE
Visual regression page design

### PR DESCRIPTION
**Pull request by YaronMiro**
#246

### CODE REVIEW

**Comment by YaronMiro** [comment]
**Design**
selection_147

**Comment by amitaibu** [comment]
There's a filter of repos on that page. Can you please confirm its still there.

**Comment by YaronMiro** [comment]
@amitaibu ^^
I'm aware it exist. It's hidden if you have a single repository.
selection_150

**Comment by YaronMiro** [comment]
Resolved on #291.

**Pull request closed without merging**
