### PR TITLE
Add configurable interval for CI build

### PR DESCRIPTION
**Pull request by solker**
#100

### CODE REVIEW

**Comment by solker** [comment]
We should update all old CI builds to new intervals.

**Comment by amitaibu** [comment]
> We should update all old CI builds to new intervals.

Lets do it in a follow up issue as a drush script.

**Comment by solker** [comment]
Need to figure out why travis failed.

**Comment by solker** [comment]
@amitaibu fixed, make review please.

**Comment by amitaibu** [comment]
Merged (not including the script, which I'll use for upgrade, but keep out of the "clean" repo).

**Pull request closed without merging**
