### PR TITLE
Add CI Buil badge link

### PR DESCRIPTION
**Pull request by HelenaEksler**
#316

### CODE REVIEW

**Comment by HelenaEksler** [comment]
selection_062

@YaronMiro please, advice on design.

**Comment by amitaibu** [comment]
Badge url should be in markdown format with link to the shoov repo.

**Comment by HelenaEksler** [comment]
@amitaibu `Badge` - this format?

**Comment by amitaibu** [comment]
See the examples we have in the readme - with the travis badge.

**Comment by HelenaEksler** [comment]
> See the examples we have in the readme - with the travis badge.

In which readme?

**Comment by amitaibu** [comment]
In every project we have travis. Similar to the format you wrote, but not
in front a computer so can't give you the exact one.

**Comment by HelenaEksler** [comment]
selection_065

**Comment by amitaibu** [comment]
Merged.

**Pull request closed without merging**
