### PR TITLE
Add filtering to the re-queued items view.

### PR DESCRIPTION
**Pull request by HelenaEksler**
#361

### CODE REVIEW

**Comment by HelenaEksler** [comment]
Exposed filter for message status:
selection_042

No items with re-queue count 0:
selection_043

**Comment by HelenaEksler** [comment]
@amitaibu Ready

**Comment by amitaibu** [comment]
Status filter should be multiple. Also please fix the label of the filter

**Comment by HelenaEksler** [comment]
@amitaibu Done.
selection_046

**Pull request merged**
