### PR TITLE
Add animate for new pushed builds.

### PR DESCRIPTION
**Pull request by nedSaf**
#146

### CODE REVIEW

**Comment by nedSaf** [comment]
@amitaibu Animation:
animation

**Comment by amitaibu** [comment]
Thanks. Lets also add to this PR animation for the `repos/[id]` page

**Comment by nedSaf** [comment]
@amitaibu I've added the class to the `repos/[id]` page, Not sure how to test it.

**Comment by nedSaf** [comment]
@amitaibu Repos animation:
animation

**Comment by nedSaf** [comment]
@amitaibu It adds builds in a weird way, Should we change that here ?
animation

**Comment by nedSaf** [comment]
@amitaibu 
animation 1

**Comment by nedSaf** [comment]
@amitaibu PR is ready.

**Comment by amitaibu** [comment]
Merged.

**Pull request closed without merging**
