### PR TITLE
Make ci build items list a table

### PR DESCRIPTION
**Pull request by nedSaf**
#159

### CODE REVIEW

**Comment by nedSaf** [comment]
Update: @amitaibu How does this look ?
localhost_9000___repos_22

**Comment by nedSaf** [comment]
Update: New animation (Fixed by separating items).
animation

**Comment by amitaibu** [comment]
Looks great

**Comment by nedSaf** [comment]
Added a table for incidents: 
localhost_9000___repos_22

**Comment by nedSaf** [comment]
@amitaibu PR is ready for code review.

**Comment by amitaibu** [comment]
Merged, looks good - thanks.

**Pull request closed without merging**
