### PR TITLE
Login page design

### PR DESCRIPTION
**Pull request by YaronMiro**
#243

### CODE REVIEW

**Comment by YaronMiro** [comment]
**Login page:**
selection_118

selection_120

**Comment by amitaibu** [comment]
Lets remove the dev steps - they had no positive impact so far

**Comment by YaronMiro** [comment]
@amitaibu  ^^ Removed `dev tips`
selection_121

**Comment by amitaibu** [comment]
IMO the grey text isn't very readable

**Comment by amitaibu** [comment]
Also we can probably remove the double "Sign In" :)

**Comment by YaronMiro** [comment]
**Progress update:**
selection_127

**Comment by YaronMiro** [comment]
**Progress update:**
selection_008

**Comment by YaronMiro** [comment]
Resolved on #279.

**Pull request closed without merging**
