### PR TITLE
Theme the CI build item page view in the client

### PR DESCRIPTION
**Pull request by nedSaf**
#165

### CODE REVIEW

**Comment by nedSaf** [comment]
#### Error build:

localhost_9000__code_264a3df57093e2cc4d52__ci-build-items_38

#### Done build:

localhost_9000__code_264a3df57093e2cc4d52__ci-build-items_37

#### Queue build:

localhost_9000__code_264a3df57093e2cc4d52__ci-build-items_39

#### In progress build:

localhost_9000__code_264a3df57093e2cc4d52__ci-build-items_39

**Comment by nedSaf** [comment]
@amitaibu PR is ready for code review.

**Comment by amitaibu** [comment]
Can you also add breadcrumbs please

**Comment by nedSaf** [comment]
@amitaibu Breadcrumbs added:
localhost_9000__code_348fcfe6a8914e8f9f62__ci-build-items_38

**Comment by amitaibu** [comment]
`#38` => `Build #38`

**Comment by nedSaf** [comment]
localhost_9000__code_348fcfe6a8914e8f9f62__ci-build-items_38

@amitaibu Should I add it in the title as well.

**Comment by nedSaf** [comment]
localhost_9000__code_348fcfe6a8914e8f9f62__ci-build-items_38

**Comment by nedSaf** [comment]
@amitaibu Ready.

**Comment by amitaibu** [comment]
Merged, thanks.

**Pull request closed without merging**
